---
:dynamic: true
:concurrency: 1
:queues:
  - default
  - mailers
  - scrapper_jobs
  - dynamic_scrapper_jobs
  - daily_job_notification
  - weekly_job_notification
  - weekly_2_job_notification
  - monthly_job_notification
  - yearly_job_notification
:schedule:
#   # auto_renewal_subscriptions:
#   #   cron: '59 23 * * * *'
#   #   class: SubscriptionAutoRenewal


  # auto_renewal_subscriptions:
  #   cron: '59 23 * * * *'
  #   class: SubscriptionAutoRenewal

  scrap_job_worker:
    cron: '0 23 13 * * *'
    class: ScrapJobWorker
  dynamic_scrap_worker:
    cron: '0 25 13 * * *'
    class: DynamicScrapWorker
  # daily_email_worker:
  #   cron: "0 0 4 * * *" #Every Day at 4am assuming scrapping will take 3-4 hours
  #   class: DailyEmailWorke
  # weekly_email_worker:
  #   every: ["1m"] #"0 0 4 * * MON"
  #   class: WeeklyEmailWorker
  # two_week_email_worker:
  #   every: ["2w"]
  #   class: TwoWeekEmailWorker
  # monthly_email_worker:
  #   every: ["4w"] #"0 0 4 1 * MON"
  #   class: MonthlyEmailWorker
  # yearly_email_worker:
  #   every: ["52w"]
  #   class: YearlyEmailWorker


    # daily_email_worker:
    #   cron: '0 0 0 * * *'
    #   class: DailyEmailWorker

    # weekly_email_worker:
    #   cron: '0 0 0 * * 1'
    #   class: WeeklyEmailWorker

    # two_week_email_worker:
    #   cron: '0 0 0 * * 4/14'
    #   class: TwoWeekEmailWorker

    # monthly_email_worker:
    #   cron: '0 0 0 * */1 1'
    #   class: MonthlyEmailWorker

    # yearly_email_worker:
    #   cron: '0 0 0 * */12 1'
    #   class: YearlyEmailWorker
